"""Generate nginx reverse-proxy config from device hostname → Tailscale IP mappings.

When nginx-proxy mode is enabled the syncer writes one ``.conf`` file per
device into the configured config directory, then reloads nginx so traffic
hitting the public IP on the right Host header is forwarded to the device
over Tailscale.
"""

from __future__ import annotations

import logging
import subprocess
import time
from pathlib import Path

logger = logging.getLogger(__name__)

NGINX_UPSTREAM_TPL = """# Auto-generated by tailnet-dns-syncer — do not edit manually
# Last updated: {timestamp}

server {{
    listen 80;
    server_name {hostname};

    location / {{
        proxy_pass http://{tailscale_ip}:{backend_port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}
}}
"""


def write_device_config(
    config_dir: str,
    hostname: str,
    tailscale_ip: str,
    backend_port: int,
) -> Path | None:
    """Write an nginx ``server`` block for one device.

    Returns the path of the written file, or ``None`` if nothing changed.
    """
    content = NGINX_UPSTREAM_TPL.format(
        hostname=hostname,
        tailscale_ip=tailscale_ip,
        backend_port=backend_port,
        timestamp=time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime()),
    )

    path = Path(config_dir) / f"{hostname}.conf"
    path.parent.mkdir(parents=True, exist_ok=True)

    existing = path.read_text() if path.exists() else ""
    if existing == content:
        logger.debug("nginx config for %s unchanged", hostname)
        return None

    path.write_text(content)
    logger.info("Wrote nginx config for %s → %s:%d", hostname, tailscale_ip, backend_port)
    return path


def remove_device_config(config_dir: str, hostname: str) -> bool:
    """Delete the nginx config file for a device that left the tailnet."""
    path = Path(config_dir) / f"{hostname}.conf"
    if path.exists():
        path.unlink()
        logger.info("Removed nginx config for %s (device left tailnet)", hostname)
        return True
    return False


def reload_nginx(cmd: str = "nginx -s reload") -> bool:
    """Signal nginx to reload its config.  Returns True on success."""
    try:
        result = subprocess.run(
            cmd.split(),
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            logger.info("nginx reloaded successfully")
            return True
        logger.warning("nginx reload failed (code %d): %s", result.returncode, result.stderr.strip())
        return False
    except FileNotFoundError:
        logger.warning("nginx binary not found — skipping reload (config files written)")
        return False
    except subprocess.TimeoutExpired:
        logger.warning("nginx reload timed out")
        return False
